shop/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import RegisterView, RegisterActivateView, UserDetailView, \
    UserChangeView, UserPasswordChangeView, UserPasswordResetEmailView, UserPasswordResetView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='create'),
    path('activate/<uuid:token>/', RegisterActivateView.as_view(), name='activate'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', UserChangeView.as_view(), name='change'),
    path('password-change/', UserPasswordChangeView.as_view(), name='password_change'),
    path('password-reset/', UserPasswordResetEmailView.as_view(), name='password_reset_email'),
    path('password-reset/<uuid:token>/', UserPasswordResetView.as_view(), name='password_reset')
]

shop/api/urls.py
from django.contrib import admin
from django.urls import path, include
from api.views import RegisterView, ItemListView, UserEdit

urlpatterns = [
    path('register/', RegisterView.as_view()),
    path('items/', ItemListView.as_view()),
    path('user/update/<int:pk>/', UserEdit.as_view()),
    

]

shop/main/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from webapp.views import *
from django.urls import reverse

urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include('accounts.urls')),
    path('api/v1/auth/', include('rest_framework.urls')),
    path('api/v1/', include('api.urls')),
    # path('', index, name='index'),
    path('', IndexView.as_view(), name='index'),
    path('category/<slug:category>/<slug:subcategory>/',
         CategoryListView.as_view(), name='subcategory'),
    path('category/<slug:subcategory>/',
         CategoryListView.as_view(), name='category'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/accounts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from uuid import uuid4
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser
from django.utils.timezone import now
from datetime import timedelta

User._meta.get_field('email')._unique = True
User._meta.get_field('email').blank = False
User._meta.get_field('email').null = False

TOKEN_TYPE_REGISTER = 'register'
TOKEN_TYPE_PASSWORD_RESET = 'password_reset'
TOKEN_TYPE_CHOICES = (
    (TOKEN_TYPE_REGISTER, 'Регистрация'),
    (TOKEN_TYPE_PASSWORD_RESET, 'Восстановление пароля')
)


class AuthToken(models.Model):
    token = models.UUIDField(verbose_name='Токен', default=uuid4)
    user: AbstractUser = models.ForeignKey(get_user_model(), on_delete=models.CASCADE,
                                           related_name='tokens', verbose_name='Пользователь')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Создан')
    life_days = models.IntegerField(
        default=7, verbose_name='Срок действия (в днях)')
    type = models.CharField(max_length=20, choices=TOKEN_TYPE_CHOICES,
                            default=TOKEN_TYPE_REGISTER, verbose_name='Тип токена')

    @classmethod
    def get_token(cls, token):
        try:
            return cls.objects.get(token=token)
        except cls.DoesNotExist:
            return None

    def is_alive(self):
        return (self.created_at + timedelta(days=self.life_days)) >= now()

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name = 'Аутентификационный токен'
        verbose_name_plural = 'Аутентификационные токены'


class Profile(models.Model):
    user: AbstractUser = models.OneToOneField(get_user_model(), related_name='profile',
                                              on_delete=models.CASCADE, verbose_name='Пользователь')
    birth_date = models.DateField(
        null=True, blank=True, verbose_name='Дата рождения')
    avatar = models.ImageField(
        null=True, blank=True, upload_to='user_pics', verbose_name='Аватар')

    def __str__(self):
        return self.user.get_full_name() + "'s Profile"

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'

shop/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from django.urls import reverse
from django.conf import settings
from django import forms
from django.contrib.auth import get_user_model

from .models import AuthToken, Profile, TOKEN_TYPE_PASSWORD_RESET


class MyUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = ['username', 'email', 'password1', 'password2',
                  'first_name', 'last_name']

    def save(self, commit=True):
        if settings.ACTIVATE_USERS_EMAIL:
            user: AbstractUser = super().save(commit=False)
            user.is_active = False
            if commit:
                user.save()
                token = self.create_token(user)
                self.send_email(user, token)
        else:
            user = super().save(commit=commit)
            Profile.objects.create(user=user)
        return user

    def create_token(self, user):
        return AuthToken.objects.create(user=user)

    def send_email(self, user, token):
        if user.email:
            subject = 'Вы создали учётную запись на сайте "Мой Блог"'
            link = settings.BASE_HOST + \
                reverse('accounts:activate', kwargs={'token': token.token})
            message = f'''Здравствуйте, {user.username}!
Вы создали учётную запись на сайте "Мой Блог"
Активируйте её, перейдя по ссылке {link}.
Если вы считаете, что это ошибка, просто игнорируйте это письмо.'''
            html_message = f'''Здравствуйте, {user.username}!
Вы создали учётную запись на сайте "Мой Блог"
Активируйте её, перейдя по ссылке <a href="{link}">{link}</a>.
Если вы считаете, что это ошибка, просто игнорируйте это письмо.'''
            try:
                user.email_user(subject, message, html_message=html_message)
            except Exception as e:
                print(e)


class UserChangeForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email']
        labels = {'first_name': 'Имя',
                  'last_name': 'Фамилия', 'email': 'Email'}


class ProfileChangeForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['user']


class SetPasswordForm(forms.ModelForm):
    password = forms.CharField(
        label="Новый пароль", strip=False, widget=forms.PasswordInput)
    password_confirm = forms.CharField(
        label="Подтвердите пароль", widget=forms.PasswordInput, strip=False)

    def clean_password_confirm(self):
        password = self.cleaned_data.get("password")
        password_confirm = self.cleaned_data.get("password_confirm")
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Пароли не совпадают!')
        return password_confirm

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    class Meta:
        model = get_user_model()
        fields = ['password', 'password_confirm']


class PasswordChangeForm(SetPasswordForm):
    old_password = forms.CharField(
        label="Старый пароль", strip=False, widget=forms.PasswordInput)

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')
        if not self.instance.check_password(old_password):
            raise forms.ValidationError('Старый пароль неправильный!')
        return old_password

    class Meta:
        model = get_user_model()
        fields = ['password', 'password_confirm', 'old_password']


class PasswordResetEmailForm(forms.Form):
    email = forms.EmailField(required=True, label='Email')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        User = get_user_model()
        if User.objects.filter(email=email).count() == 0:
            raise ValidationError(
                'Пользователь с таким email-ом не зарегистрирован')
        return email

    def send_email(self):
        User = get_user_model()
        email = self.cleaned_data.get('email')
        user = User.objects.filter(email=email).first()
        token = AuthToken.objects.create(
            user=user, life_days=3, type=TOKEN_TYPE_PASSWORD_RESET)

        subject = 'Вы запросили восстановление пароля для учётной записи на сайте "Мой Блог"'
        link = settings.BASE_HOST + \
            reverse('accounts:password_reset', kwargs={'token': token.token})
        message = f'''Ваша ссылка для восстановления пароля: {link}.
Если вы считаете, что это ошибка, просто игнорируйте это письмо.'''
        html_message = f'''Ваша ссылка для восстановления пароля: <a href="{link}">{link}</a>.
Если вы считаете, что это ошибка, просто игнорируйте это письмо.'''
        try:
            user.email_user(subject, message, html_message=html_message)
        except Exception as e:
            print(e)


class PasswordResetForm(SetPasswordForm):
    pass

shop/accounts/views.py
from django.contrib.auth import get_user_model, authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import PasswordChangeView, \
    PasswordResetView, PasswordResetConfirmView
from django.core.mail import send_mail
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import View, FormView, DetailView, CreateView, UpdateView
from django.conf import settings

from accounts.forms import MyUserCreationForm, UserChangeForm, ProfileChangeForm, \
    PasswordChangeForm, PasswordResetEmailForm, PasswordResetForm
from .models import AuthToken, Profile
from django.http import HttpResponse, JsonResponse
import os


class RegisterView(CreateView):
    model = User
    template_name = 'user_create.html'
    form_class = MyUserCreationForm

    def form_valid(self, form):
        user = form.save()
        if settings.ACTIVATE_USERS_EMAIL:
            return redirect('index')
        else:
            login(self.request, user)
            return redirect(self.get_success_url())

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if not next_url:
            next_url = self.request.POST.get('next')
        if not next_url:
            next_url = reverse('index')
        return next_url


class RegisterActivateView(View):
    def get(self, request, *args, **kwargs):
        token = AuthToken.get_token(self.kwargs.get('token'))
        if token:
            if token.is_alive():
                self.activate_user(token)
            token.delete()
        return redirect('index')

    def activate_user(self, token):
        user = token.user
        user.is_active = True
        user.save()
        Profile.objects.create(user=user)
        login(self.request, user)


class UserDetailView(LoginRequiredMixin, DetailView):
    model = get_user_model()
    template_name = 'user_detail.html'
    context_object_name = 'user_obj'
    paginate_related_by = 5
    paginate_related_orphans = 0

    def get_context_data(self, **kwargs):
        return super().get_context_data(**kwargs)


class UserChangeView(UserPassesTestMixin, UpdateView):
    model = get_user_model()
    form_class = UserChangeForm
    template_name = 'user_change.html'
    context_object_name = 'user_obj'

    def test_func(self):
        return self.request.user == self.get_object()

    def get_context_data(self, **kwargs):
        if 'profile_form' not in kwargs:
            kwargs['profile_form'] = self.get_profile_form()
        return super().get_context_data(**kwargs)

    def post(self, *args, **kwargs):
        if self.request.is_ajax and self.request.method == "POST":
            self.object = self.get_object()
            profile_form = self.get_profile_form(self.request.POST)
            form = self.get_user_form(self.request.POST)
            if form.is_valid() and profile_form.is_valid():
                profile_form.save()
                form.save()
                return HttpResponse('')
            else:
                return HttpResponse('')

        return HttpResponse('')

    def get_success_url(self, req):
        return reverse('accounts:detail', kwargs={'pk': self.object.pk})

    def get_profile_form(self, *args, **kwargs):
        form_kwargs = {'instance': self.object.profile}
        if self.request.method == 'POST':
            form_kwargs['data'] = self.request.POST
            form_kwargs['files'] = self.request.FILES
        return ProfileChangeForm(**form_kwargs)

    def get_user_form(self, *args, **kwargs):
        form_kwargs = {'instance': self.object}
        if self.request.method == 'POST':
            form_kwargs['data'] = self.request.POST
            form_kwargs['files'] = self.request.FILES
        return UserChangeForm(**form_kwargs)


class UserPasswordChangeView(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    template_name = 'user_password_change.html'
    form_class = PasswordChangeForm
    context_object_name = 'user_obj'

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        user = form.save()
        update_session_auth_hash(self.request, user)
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('accounts:detail', kwargs={'pk': self.object.pk})


class UserPasswordResetEmailView(FormView):
    form_class = PasswordResetEmailForm
    template_name = 'password_reset_email.html'
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        form.send_email()
        return super().form_valid(form)


class UserPasswordResetView(UpdateView):
    model = User
    form_class = PasswordResetForm
    template_name = 'password_reset.html'
    success_url = reverse_lazy('accounts:login')

    def get_object(self, queryset=None):
        token = self.get_token()
        if token and token.is_alive():
            return token.user
        raise Http404('Ссылка не существует или её срок действия истёк')

    def form_valid(self, form):
        token = self.get_token()
        token.delete()
        return super().form_valid(form)

    def get_token(self):
        return AuthToken.get_token(self.kwargs.get('token'))

# class ProfileEditView(UpdateView):
#     model = Profile
#     form_class =

shop/accounts/templates/password_reset.html
{% extends 'base.html' %}

{% block title %}Восстановление пароля{% endblock %}

{% block content %}
<div class="panel">
    <div class="panel_title">
        <h2>Восстановление пароля</h2>
    </div>
    <div class="panel_body">
        {% include 'partial/form.html' with form_method="post" %}
    </div>
</div>
{% endblock %}

shop/accounts/templates/password_reset_email.html
{% extends 'base.html' %}

{% block title %}Восстановление пароля{% endblock %}

{% block content %}
<div class="panel">
    <div class="panel_title">
        <h2>Восстановление пароля</h2>
    </div>
    <div class="panel_body">
        {% url "accounts:password_reset_email" as action_url %}
        {% include 'partial/form.html' with action_url=action_url form_method="post" %}
    </div>
</div>
{% endblock %}

shop/accounts/templates/user_change.html
{% extends 'base.html' %}


{% block title %}Редактировать пользователя{% endblock %}

{% block menu %}
<li><a href="{% url "accounts:detail" user_obj.pk %}">Назад</a></li>
<li><a href="{% url "accounts:password_change" %}">Смена пароля</a></li>
{% endblock %}

{% block content %}
<div class="panel">
    <div class="panel_title">
        <h2>Поменять личные данные</h2>
    </div>
    <div class="panel_body">
        <form id='user_form' action="{% url 'accounts:change' user_obj.pk %}" method="post"
            enctype="multipart/form-data">
            {% csrf_token %}
            {% include 'partial/twoforms.html' with form1=form form2=profile_form fields_only=True button_class="btn_update" button_text="Сохранить" %}
            {% comment %} {% include 'partial/form.html' with form=form fields_only=True button_class='hidden' %}
        </form>
        <form id='profile_form' action="{% url 'accounts:change' user_obj.pk %}" method="post"
            enctype="multipart/form-data">
            {% include 'partial/form.html' with form=profile_form fields_only=True %} {% endcomment %}
        </form>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<script>
    $('form').submit(function (event) {
        event.preventDefault();
        let data = $('#user_form').serialize();
        $.ajax({
            type: "POST",
            dataType: 'html',
            enctype: "multipart/form-data",
            url: "{% url 'accounts:change' user_obj.pk %}",
            data: data,
            success: function (data, tst, xhr) {
                console.log('XHR OK');
            },
            error: function (xhr, tst, err) {
                console.log('XHR ERROR ' + XMLHttpRequest.status);
                console.log(data);
            },

        });
    })
</script>
{% comment %} <script>
    function submitForm1(e) {
        e.preventdefault()
        var data = $('#user_form').serialize();
        return $.ajax({
            type: "POST",
            dataType: 'html',
            url: "{% url 'accounts:change' user_obj.pk %}",
            data: data,
            enctype: "multipart/form-data",
            success: function (data, tst, xhr) {
                $.log('XHR OK');
            },
            error: function (xhr, tst, err) {
                $.log('XHR ERROR ' + XMLHttpRequest.status);
                $.log(data);
            },
        });
    };

    function submitForm2(e) {
        e.preventdefault()
        var data = $('#profile_form').serialize();
        return $.ajax({
            type: "POST",
            dataType: 'html',
            url: "{% url 'accounts:change' user_obj.pk %}",
            data: data,
            enctype: "multipart/form-data",
            success: function (data, tst, xhr) {
                $.log('XHR OK');
            },
            error: function (xhr, tst, err) {
                $.log('XHR ERROR ' + XMLHttpRequest.status);
                $.log(data);
            },
        });
    };

    submitForm1().done(function () {
        submitForm2();
    });
</script> {% endcomment %}

{% endblock scripts %}

shop/accounts/templates/user_create.html
{% extends 'base.html' %}

{% block title %}Регистрация{% endblock %}

{% block auth_menu %}
{% with request.GET.next as next_url %}
<li><a href="{% url 'accounts:login' %}{% if next_url %}?next={{ next_url }}{% endif %}">Вход</a></li>
<li><a href="{% url 'accounts:create' %}{% if next_url %}?next={{ next_url }}{% endif %}">Регистрация</a></li>
{% endwith %}
{% endblock %}

{% block content %}
<div class="panel">
    <div class="panel_title">
        <h2>Регистрация</h2>
    </div>
    <div class="panel_body">
        {% include 'partial/form.html' with form_method='post' button_text="Зарегистрироваться" %}
    </div>
</div>
{% endblock %}

shop/accounts/templates/user_detail.html
{% extends 'base.html' %}

{% block title %}Пользователь{% endblock %}

{% block menu %}
{% if request.user == user_obj %}
<li><a href="{% url 'accounts:change' user_obj.pk %}">Редактировать</a></li>
<li><a href="{% url "accounts:password_change" %}">Смена пароля</a></li>
{% endif %}
{% endblock %}

{% block content %}
<div class="panel">
    <div class="panel_title">
        <h2>Личная страница:</h2>
        <h3>{{ user_obj.get_full_name|default:user_obj.username }}</h3>
    </div>
    <div class="panel_body">
        <div class="list">
            <div>
                {% if user_obj.profile.avatar %}
                <img class="avatar" src="{{ user_obj.profile.avatar.url }}" alt="user picture">
                {% endif %}
            </div>
            <div>
                <p class="text"><strong>Имя пользователя:</strong> {{ user_obj.username }}</p>
                <p class="text"><strong>Имя:</strong> {{ user_obj.first_name }}</p>
                <p class="text"><strong>Фамилия:</strong> {{ user_obj.last_name }}</p>
                <p class="text"><strong>Дата рождения:</strong> {{ user_obj.profile.birth_date|date:'d.m.Y' }}</p>
                <p class="text"><strong>Почта:</strong> {{ user_obj.email }}</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

shop/accounts/templates/user_password_change.html
{% extends 'base.html' %}

{% block title %}Смена пароля{% endblock %}

{% block menu %}
<li><a href="{% url "accounts:detail" request.user.pk %}">Назад</a></li>
<li><a href="{% url "accounts:change" request.user.pk %}">Редактирование личных данных</a></li>
{% endblock %}

{% block content %}
<div class="panel">
    <div class="panel_title">
        <h2>Смена пароля</h2>
    </div>
    <div class="panel_body">
        {% url "accounts:password_change" as action_url %}
        {% include 'partial/form.html' with action_url=action_url form_method="post" %}
    </div>
</div>
{% endblock %}