shop/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import RegisterView, RegisterActivateView, UserDetailView, \
    UserChangeView, UserPasswordChangeView, UserPasswordResetEmailView, UserPasswordResetView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='create'),
    path('activate/<uuid:token>/', RegisterActivateView.as_view(), name='activate'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', UserChangeView.as_view(), name='change'),
    path('password-change/', UserPasswordChangeView.as_view(), name='password_change'),
    path('password-reset/', UserPasswordResetEmailView.as_view(), name='password_reset_email'),
    path('password-reset/<uuid:token>/', UserPasswordResetView.as_view(), name='password_reset')
]

shop/api/urls.py
from django.contrib import admin
from django.urls import path, include
from api.views import RegisterView, ItemListView, UserEdit

urlpatterns = [
    path('register/', RegisterView.as_view()),
    path('items/', ItemListView.as_view()),
    path('user/update/<int:pk>/', UserEdit.as_view()),
    

]

shop/main/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from webapp.views import *
from django.urls import reverse

urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include('accounts.urls')),
    path('api/v1/auth/', include('rest_framework.urls')),
    path('api/v1/', include('api.urls')),
    # path('', index, name='index'),
    path('', IndexView.as_view(), name='index'),
    path('category/<slug:category>/<slug:subcategory>/',
         CategoryListView.as_view(), name='subcategory'),
    path('category/<slug:subcategory>/',
         CategoryListView.as_view(), name='category'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/webapp/models.py
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey
from django.utils.translation import ugettext_lazy as _
from django.urls import reverse


class Category(MPTTModel):
    name = models.CharField(verbose_name=_("Название"),
                            max_length=50, unique=True)
    slug = models.SlugField(unique=True)
    parent = TreeForeignKey('self', verbose_name=_("Родитель"), on_delete=models.CASCADE,
                            null=True, blank=True, related_name='children')

    def get_absolute_url(self):
        if self.parent_id:
            return reverse(
                'subcategory',
                kwargs={'category': self.parent.slug,
                        'subcategory': self.slug}
            )
        else:
            return reverse('category', kwargs={'subcategory': self.slug})

    class MPTTMeta:
        level_attr = 'mptt_level'
        order_insertion_by = ['name']

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

# Create your models here.


class Item(models.Model):
    name = models.CharField(
        max_length=40, verbose_name=_("Название"), db_index=True)
    description = models.CharField(max_length=250, verbose_name=_("Описание"))
    price = models.PositiveIntegerField(verbose_name=_('Цена'))
    category = models.ForeignKey(
        "webapp.Category", verbose_name=_("Категория"), on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self):
        return self.name

shop/webapp/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404
from django.views.generic import ListView, DetailView
from webapp.models import Category, Item
from django.core.paginator import Paginator, PageNotAnInteger
from django.utils import timezone
from django.urls import reverse
from django.db.models import Q
import mptt

# Create your views here.


def index(request):
    return render(request, ('base.html'))


class IndexView(ListView):
    model = Item
    template_name = 'webapp/index_view.html'
    paginate_by = 6

    def get_queryset(self):
        queryset = Item.objects.all()
        return queryset

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        items = self.get_queryset()
        paginator = Paginator(items, self.paginate_by)

        page = self.request.GET.get('page')

        try:
            items = paginator.page(page)
        except PageNotAnInteger:
            items = paginator.page(1)
        except EmptyPage:
            items = paginator.page(paginator.num_pages)

        context = {'items': items,
                   'category': Category.objects.all()
                   }
        return context


class CategoryListView(ListView):
    model = Item
    template_name = 'webapp/index_view.html'
    paginate_by = 6

    def get_queryset(self):
        queryset = Item.objects.filter(Q(category__slug=self.kwargs.get(
            'subcategory')) | Q(category__parent__slug=self.kwargs.get('subcategory')))
        return queryset

    def get_context_data(self, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        items = self.get_queryset().order_by('id')
        paginator = Paginator(items, self.paginate_by)

        page = self.request.GET.get('page')

        try:
            items = paginator.page(page)
        except PageNotAnInteger:
            items = paginator.page(1)
        except EmptyPage:
            items = paginator.page(paginator.num_pages)

        context = {'items': items,
                   'category': Category.objects.all()
                   }
        return context

    # queryset = {'items': Item.objects.filter(category_id=self.kwargs.get('pk')),
    #             'category': Category.objects.all()}
    # return queryset

shop/webapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Sunrise Studio test {% endblock title %}</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block links %}{% endblock %}
</head>

<body>
    <div class="back">
        <nav class="navbar">
            <div class="container">
                <ul class="menu">
                    <li><a href="{% url 'index' %}">Home</a></li>
                    {% if request.user.is_authenticated %}
                    <li><a href="{% url 'accounts:detail' request.user.pk %}">Профиль</a></li>
                    {% block menu %}{% endblock %}
                    {% endif %}
                    {% block auth_menu %}
                    {% if request.user.is_authenticated %}
                    <li><a href="{% url 'accounts:logout' %}?next={{ request.get_full_path }}">Выход</a></li>
                    {% else %}
                    <li><a href="{% url 'accounts:login' %}?next={{ request.get_full_path }}">Вход</a></li>
                    <li><a href="{% url 'accounts:create' %}?next={{ request.get_full_path }}">Регистрация</a></li>
                    {% endif %}
                    {% endblock %}
                    {% if not request.user.is_authenticated %}
                    <li><a href="{% url 'accounts:password_reset_email' %}">Cброс пароля</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>

        {% block sidebar %}
        {% endblock sidebar %}
        {% block content %}
        {% endblock content %}
        <div class="circle" id='circle2'></div>
        <div class="circle" id='circle1'></div>
        <div class="square" id='square1'></div>
        <div class="square" id='square2'></div>
        <div class="square" id='square3'></div>
    </div>
    {% block scripts %}{% endblock %}
</body>

</html>